import Sidebar from "@/layout/sidebar/Sidebar";
import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <main className="microgen_dx">
          <Sidebar />
          {children}
        </main>
      </body>
    </html>
  );
}
